project_name: kez
version: 2

release:
  name_template: kez {{.Version}}
  draft: true
  replace_existing_draft: true
  prerelease: auto
  make_latest: false
  mode: replace

changelog:
  use: github

builds:
  - id: macos
    goos: [darwin]
    goarch: [amd64, arm64]
    binary: kez
    main: ./main.go
    ldflags:
      - -s -w -X github.com/mcncl/kez/internal/version.Version={{.Version}}

  - id: linux
    goos: [linux]
    goarch: [arm, amd64, arm64]
    env:
      - CGO_ENABLED=0
    binary: kez
    main: ./main.go
    ldflags:
      - -s -w -X github.com/mcncl/kez/internal/version.Version={{.Version}}

  - id: windows
    goos: [windows]
    goarch: [amd64, arm64]
    binary: kez
    main: ./main.go
    ldflags:
      - -s -w -X github.com/mcncl/kez/internal/version.Version={{.Version}}

archives:
  - id: macos-archive
    builds: [macos]
    name_template: "kez_{{ .Version }}_macOS_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: zip
    files:
      - LICENSE.md
      - README.md

  - id: linux-archive
    builds: [linux]
    name_template: "kez_{{ .Version }}_linux_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE.md
      - README.md

  - id: windows-archive
    builds: [windows]
    name_template: "kez_{{ .Version }}_windows_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
    wrap_in_directory: false
    format: zip
    files:
      - LICENSE.md
      - README.md

nfpms:
  - builds:
      - linux
    vendor: kez 
    homepage: https://github.com/mcncl/kez
    maintainer: Ben McNicholl <git@benmcnicholl.com>
    description: A CLI tool for spinning up local Buildkite k8s stacks.
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    provides:
      - kez
